print("----------------------------------------------")
print("Tread Python Package - Data Science ----------")
print("Made By: Ashish Jayamohan --------------------")
print("------------------------------- Setup Complete")
print("------------------------ All Packages Imported")
print("----------------------------------------------")
